apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: integration-dashboard
  description: Show all integrations
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Rekha1908/Backstage
relations:
  - type: ownedBy
    targetRef: group:default/guests
  - type: partOf
    targetRef: system:default/examples
  - type: providesApi
    targetRef: api:default/example-grpc-api
spec:
  type: service
  lifecycle: production
  owner: Rekha
