apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: integration-dashboard
  description: show all integrations
links:
  - url: http://localhost:3000/integration
    title: Integration Catlog
    icon: dashboard
    type: admin-dashboard
spec:
  type: service
  lifecycle: production
  owner: Rekha
 
